### ISSUE TITLE
project source file locations suggestion

### ISSUE THREAD

**Issue by PhyrexianHulk** [ThomasLoke/stock_cutter#1]
why not change the vcxproj source file paths from:
..\..\..\..\..\..\..\My Pug%27s Stuff\OneDrive\Main repository\WorkBunny\Victor work!\
to something else?

**Comment by ThomasLoke** [comment]
Thanks for pointing that out--I've removed all the visual studio specific paths from this, and I'll leave it up to any users to make their own visual studio project :)
